import Head from "next/head";
import Link from "next/link";
import AppLayout from "../components/AppLayout";
import Button from "../components/Button";
import GitHub from "../components/GitHub";
import { colors } from "../styles/theme";
import { loginWithGitHub } from "../firebase/client";
export default function Home() {

  const handleClick = () => {
    loginWithGitHub()
  }
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <AppLayout>
      <section>
        <img src="/logo.jpg" />
        <h1>Devter</h1>
        <h2>Talk about development with developers</h2>
        <Button onClick={handleClick}>
          <GitHub fill="#fff"/>
          Login with GitHub
        </Button>
      </section>
    </AppLayout>
    <style jsx>{`
      section{
        display: grid;
        height: 100%;
        place-content: center;
        place-items: center;
      }
      img{
        width: 120px
      }
      h1{
        color: ${colors.secondary};
        font-weight: 800;
        margin-bottom: 16px;
      }
      h2{
        color: ${colors.primary};
        font-size: 21px;
        margin-bottom: 16px;
        margin-top: 0;
      }
    `}</style>
  </>
  );
}
