import { useState, useEffect } from "react";
import Head from "next/head";
import AppLayout from "components/AppLayout";
import { Devit } from "components/Devit";

const HomePage = () => {
  const [timeline, setTimeline] = useState([]);
  useEffect(() => {
    fetch("http://localhost:3000/api/statuses/home_timeline")
      .then((res) => res.json())
      .then(setTimeline);
  }, []);
  return (
    <>
      <Head>
        <title>Inicio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <header>
          <h2>Inicio</h2>
        </header>
        <section>
          {timeline.map(({ avatar, username, message, id }) => {
            return (
              <Devit
                key={id}
                avatar={avatar}
                username={username}
                message={message}
                id={id}
              />
            );
          })}
        </section>
        <nav></nav>
        <style jsx>{`
          header {
            align-items: center;
            backdrop-filter: blur(5px);
            background: #ffffffaa;
            border-bottom: 1px solid #eee;
            display: flex;
            height: 49px;
            position: sticky;
            top: 0;
            width: 100%;
          }
          h2 {
            font-weight: 700;
            font-size: 21px;
            padding-left: 15px;
          }
          nav {
            background: #ffffffee;
            bottom: 0;
            border-top: 1px solid #ee;
            height: 49px;
            position: fixed;
            width: 100%;
          }
        `}</style>
      </AppLayout>
    </>
  );
};

export default HomePage;
